name: coverage

on: [push, pull_request]

jobs:
  macos:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    strategy:
      matrix:
        r: [latest]
        # r: [3.5, 3.6, devel]
    runs-on: macOS-latest
    env:
      NOT_CRAN: true
      R_LANGSVR_LOG: /tmp/languageserver/coverage-log
      R_LANGSVR_POOL_SIZE: 1
      R_LANGSVR_TEST_FAST: NO
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.r }}
    - name: Install languagesever
      run: |
        Rscript -e "install.packages(c('remotes'), repos = 'https://cloud.r-project.org')"
        Rscript -e "remotes::install_deps(dependencies = TRUE)"
        Rscript -e "remotes::install_local()"
    - name: Codecov
      run: |
        mkdir -p /tmp/languageserver
        Rscript -e "covr::codecov(quiet = FALSE, clean = FALSE)"
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: coverage-log
        path: /tmp/languageserver
